### ISSUE TITLE
Feature Request: Support for named cells

### ISSUE THREAD

**Issue by moritz** [jmcnamara/spreadsheet-parseexcel#12]
Excel supports [named cells](https://support.microsoft.com/en-us/office/define-and-use-names-in-formulas-4d0f13ac-53b7-422e-afd2-abd7ff379c64), that is, a way to give a cell a unique name (probably scoped to the worksheet? not entirely sure) and then use this name to reference the cell, for example in formulas.

It would be very helpful for data exchange if Spreadsheet::ParseExcel could support this. In particular, we currently parse excel sheets that are used in some internal processes, and our main struggle is that folks move cells around (mostly by inserting rows or columns before or above the cell), so referencing them by name would be more stable.

My idea for the API would be:

* In `Spreadsheet::ParseExcel::Worksheet` a method `get_cell_by_name(name)` to fetch a cell based on its name
* In `Spreadsheet::ParseExcel::Cell` a method `name()` or `get_name()` to retrieve the name of the cell

**Update**: Looking at [this video on named cells](https://www.youtube.com/watch?v=tDaA3hgQwpQ), Excel allows you to reference named from a different sheet without including the sheet name, so I suspect the names are  unique per document, not just worksheet. If that is indeed the case, having the `get_cell_by_name` in `Spreadsheet::ParseExcel::Workbook` might make more sense.

**Comment by jmcnamara** [comment]
Spreadsheet::ParseExcel is mainly in maintenance mode. I took over maintenance again, after a 10 year break, to patch a critical CVE. So it is unlikely that a feature like this will be added.

Closing as "won't fix".
