### ISSUE TITLE
regex ０-９ problem in Worksheets->write()

### ISSUE THREAD

**Issue by Code-Hex** [jmcnamara/spreadsheet-parseexcel#6]
Hi, I'm japanese.
I found problem when using full-width numbers.

$worksheet->write('A1', '１２３４５６７８９', $id_format);

After, show message on my terminal.
「Argument "..." isn't numeric in addition (+) at ...」

So I thought the next of such a solution.
fix regex in write method

    # Match number
    elsif ( $token =~ /^([+-]?)(?=\d|\.\d)\d*(\.\d*)?([Ee]([+-]?\d+))?$/ ) {
        return $self->write_number( @_ );
    }

to

    # Match number
    elsif ( $token =~/^([+-]?)(?=[0-9]|\.[0-9])[0-9]*(\.[0-9]*)?([Ee]([+-]?[0-9]+))?$/ ) {
        return $self->write_number( @_ );
    }

Full-width numbers by converting from the "\d" to "[0-9]" is treated as a string, it will eliminate the error.
Thanks.

**Comment by jmcnamara** [comment]
Hi,

I think that you probably meant to post this on the spreadsheet-writeexcel or excel-writer-xlsx issue trackers.

Can reopen the issue there. Also, please attach a small working example that demonstrates the issue.

Regards,

John

**Comment by Code-Hex** [comment]
Oops...
I'm sorry, reopen the issue there.
